config/routes.rb
FileUploader2::Application.routes.draw do

  root 'data_files#index'

  devise_for :users

  resources :data_files, only: [:index, :new, :create, :destroy] do
    post 'download_file', on: :member
  end

end

app/models/data_file.rb
class DataFile
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :user
  mount_uploader :file, FileUploader

  scope :lifo, -> { order("created_at DESC")}

  validates :file, presence: true
end

app/models/user.rb
class User
  include Mongoid::Document

  has_many :data_files

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/data_files_controller.rb
class DataFilesController < ApplicationController

  before_action :authenticate_user!, except: [:index]
  before_action :is_users_file?, only: [:destroy]

  def index
    @files = DataFile.all.lifo
  end

  def new
    @file = DataFile.new
  end

  def create
    @user = current_user
    @file = @user.data_files.create(params_for_create)
    if @file.save
      flash[:notice] = t('file.create')
      redirect_to root_path
    else
      flash[:error] = @file.errors.full_messages.to_sentence
      redirect_to root_path
    end
  end

  def destroy
    @file = DataFile.find(params[:id])
    if @file.destroy
      flash[:notice] = t('file.destroy')
    else
      flash[:error] = @file.errors.full_messages.to_sentence
    end
    redirect_to root_path
  end

  def download_file
    @file = DataFile.find(params[:id])
    send_file @file.file.path,
              filename: File.basename(@file.file.path),
              type: @file.file.content_type,
              url_based_filename: true
  end

  private

  def params_for_create
    if params[:data_file].present?
      params.require(:data_file).permit(:file)
    end
  end

  def is_users_file?
    unless DataFile.find(params[:id]).user_id == current_user.id
      flash[:error] = t('file.cannot.destroy')
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/data_files/_file.html.erb
<tr>
  <td><%= File.basename(file.file.path) %></td>
  <td><%= file.created_at.to_time.strftime("%H:%M:%S %d-%m-%Y") %></td>
  <td><%= button_to "Download", download_file_data_file_path(file), :class => "btn btn-success" %></td>

  <% if current_user.id == file.user_id %>
    <td><%= link_to "Delete file", data_file_path(file), :class =>"btn btn-danger",
                method: :delete, data: {confirm: "Are you sure?"}%></td>
  <% else %>
    <td> Permission denied </td>
  <% end %>
</tr>

app/views/data_files/index.html.erb
<h3> Welcome to file uploader </h3>

<% if user_signed_in? %>
  <%=link_to "Add File", new_data_file_path, :class => "btn btn-primary" %>

  <table class="table table-striped">
    <tr>
      <th>File name</th>
      <th>Creation time</th>
      <th>Download option</th>
      <th>Delete option</th>
    </tr>
    <%= render partial: "file", collection: @files %>
  </table>

<% else %>
  <h5> Please, log in or sign up </h5>
<% end %>

app/views/data_files/new.html.erb
<%= form_for @file do |f| %>

  <%= f.label :file %>
  <%= f.file_field :file %>

  <%= f.submit "Add File", :class => "btn btn-primary"  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileUploader2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <ul class="nav">
      <li> <p class="navbar-text" style="font-size:20px">File Uploader</p></li>
      <li class="divider-vertical"></li>
      <li><%= link_to  "Home", root_path %></li>
      <li class="divider-vertical"></li>

      <% if user_signed_in? %>

      <li> <p class="navbar-text"><b>Signed in as </b><%= current_user.email%> </p></li>
        <li class="divider-vertical"></li>
        <li><%= link_to "exit", destroy_user_session_path, method: :delete %></li>
        <li class="divider-vertical"></li>

      <% else %>

        <li><%= link_to "Log in", new_user_session_path %></li>
        <li class="divider-vertical"></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li class="divider-vertical"></li>
      <% end %>

    </ul>
  </div>
</div>

<% flash.each do |name, msg|%>
  <div class="alert alert-<%= name == :notice ? "success" : "error"%>">
    <%= msg %>
  </div>
<% end %>
<%= yield %>

</body>
</html>